name: Build images

on:
  push:
  schedule:
    - cron: '0 5 * * 0'
  workflow_dispatch:
    inputs:
      use_cache:
        type: boolean
        description: "Cache layers"
        default: true

permissions:
  packages: write

env:
  USE_CACHE: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.use_cache) }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
          - bind
          - dovecot
          - elastic-aggregate
          - ffmpeg
          - fritzbox2elastic
          - g10k
          - hugo-obsidian
          - nagflux
          - ocrmypdf-inotify
          - php
          - samba

    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            files:
              - "images/${{ matrix.image }}/**"
              - .github/workflows/build.yml

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/programie/dockerimages/${{ matrix.image }}

      - uses: docker/build-push-action@v5
        if: ${{ steps.changes.outputs.files || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        with:
          context: images/${{ matrix.image }}
          push: true
          cache-from: ${{ env.USE_CACHE == 'true' && 'type=gha' || '' }}
          cache-to: type=gha,mode=max
          tags: ghcr.io/programie/dockerimages/${{ matrix.image }}
          labels: |
            org.opencontainers.image.source=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.source'] }}
            org.opencontainers.image.revision=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.revision'] }}
            org.opencontainers.image.created=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.created'] }}

  build-generic-web:
    needs: build

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php_version:
          - "7.4"
          - "8.1"

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/programie/dockerimages/generic-web:php${{ matrix.php_version }}

      - uses: docker/build-push-action@v5
        with:
          context: images/generic-web
          push: true
          cache-from: ${{ env.USE_CACHE == 'true' && 'type=gha' || '' }}
          cache-to: type=gha,mode=max
          build-args: PHP_VERSION=${{ matrix.php_version }}
          tags: ghcr.io/programie/dockerimages/generic-web:php${{ matrix.php_version }}
          labels: |
            org.opencontainers.image.source=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.source'] }}
            org.opencontainers.image.revision=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.revision'] }}
            org.opencontainers.image.created=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.created'] }}