name: Build images

on:
  push:
  schedule:
    - cron: '0 5 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
          - bind
          - dovecot
          - elastic-aggregate
          - ffmpeg
          - fritzbox2elastic
          - g10k
          - hugo-obsidian
          - nagflux
          - ocrmypdf-inotify
          - samba

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: metadata
        uses: docker/metadata-action@v5
        with:
          images: registry.gitlab.com/programie/dockerimages/${{ matrix.image }}

      - uses: docker/build-push-action@v5
        with:
          context: images/${{ matrix.image }}
          push: true
          tags: registry.gitlab.com/programie/dockerimages/${{ matrix.image }}
          labels: ${{ steps.metadata.outputs.labels }}