name: Build generic web images

on:
  push:
  schedule:
    - cron: '0 5 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php_version:
          - "7.4"
          - "8.1"

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: metadata
        uses: docker/metadata-action@v5
        with:
          images: registry.gitlab.com/programie/dockerimages/generic-web:php${{ matrix.php_version }}

      - uses: docker/build-push-action@v5
        with:
          context: images/generic-web
          push: true
          build-args: PHP_VERSION=${{ matrix.php_version }}
          tags: registry.gitlab.com/programie/dockerimages/generic-web:php${{ matrix.php_version }}